import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { Navbar } from "@/components";
import {AuthContext} from '@/context/AutContext'
import {PokemonProvider} from '@/context/PokemonContext'
import { ThemeProvider } from "@/context/themeProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <PokemonProvider>
          <ThemeProvider attribute="class" defaultTheme="dark">
              <Navbar/>
              {children}
          </ThemeProvider>
          </PokemonProvider>
        </AuthContext>
      </body>
    </html>
  );
}